version: "3.1"

services:
  websocket:
    build: .
    volumes:
      - ./src:/home/websocket-server/src
      - ./message-uploads:/home/websocket-server/message-uploads
      - ./feed-uploads:/home/websocket-server/feed-uploads
    container_name: websocket-express
    ports:
      - 80:80
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: sirily11
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sirily11
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
